version: 2.1

jobs:
  build:
    docker:
      - image: cibuilds/docker:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build a Docker Image"
          command: |
            docker build -t mfunaki/cci-img-node201218 .
      - run:
          name: "Push to DockerHub"
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USER --password-stdin && \
            docker push mfunaki/cci-img-node201218